image: billryan/gitbook:latest #gitbook/new:latest #fellah/gitbook:latest

pages:
  stage: deploy
  script:
    - gitbook install . 
    - gitbook build .
    - gitbook pdf ./ Gitbook_FACA.pdf
  only:
    - master # this job will affect only the 'master' branch
  tags:
    - gitbook
  artifacts:
    paths:
     - Gitbook_FACA.pdf
    expire_in: 1 week
