image: 10.36.94.107:5000/gitbook-plugins:latest

pages:
  stage: deploy
  script:
    - mv /node_modules ./node_modules
    - gitbook build .
    - gitbook pdf
  only:
    - master # this job will affect only the 'master' branch
  tags:
    - gitbook
  artifacts:
    paths:
     - book.pdf
    expire_in: 1 week
